// <auto-generated />
namespace App.Web.Migrations.ContextB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MadeRequiredNameForEmployeeSeveralField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MadeRequiredNameForEmployeeSeveralField));
        
        string IMigrationMetadata.Id
        {
            get { return "201711250715496_MadeRequiredNameForEmployeeSeveralField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
